fix(build): required "homepage" field in package.json
Error #3 --------------------------------------------------------------------------------
Error: Please specify project homepage, see https://electron.build/configuration/configuration#Metadata-homepage